# Generated by Django 5.1.1 on 2024-11-02 10:39

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_alter_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=cloudinary.models.CloudinaryField(
                default="default_post_ehnhuw", max_length=255, verbose_name="image"
            ),
        ),
    ]
