# Generated by Django 5.1.1 on 2024-10-22 13:26

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='../default_post_aczthl', max_length=255, verbose_name='image'),
        ),
    ]
