# Generated by Django 5.1.1 on 2024-10-22 13:50

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/dprwuhawr/image/upload/v1728378396/default_post_aczthl.jpg', max_length=255, verbose_name='image'),
        ),
    ]
