# Generated by Django 5.1.1 on 2024-10-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='../default_post_aczthl.jpg', upload_to='images/'),
        ),
    ]
