# Generated by Django 5.1.1 on 2024-11-04 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0007_alter_post_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="image_filter",
        ),
    ]
