# Generated by Django 4.2 on 2024-12-27 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0010_alter_post_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("general", "General"),
                    ("question", "Question"),
                    ("tip", "Tip"),
                ],
                default="general",
                max_length=50,
                null=True,
            ),
        ),
    ]
