# Generated by Django 5.1.1 on 2024-10-25 05:31

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=cloudinary.models.CloudinaryField(default='../default_post_aczthl', max_length=255, verbose_name='image'),
        ),
    ]
