# Generated by Django 4.2 on 2025-02-05 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0012_alter_post_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="posts", to="posts.tag"
            ),
        ),
    ]
