# Generated by Django 4.2 on 2025-02-05 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0013_tag_post_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                db_table="posts_post_tags_new",
                related_name="posts",
                to="posts.tag",
            ),
        ),
    ]
