# Generated by Django 5.1.1 on 2024-10-18 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='https://res.cloudinary.com/dprwuhawr/image/upload/v1/media/images/default_profile_b0dubq.jpg', upload_to='images/'),
        ),
    ]
