# Generated by Django 5.1.1 on 2024-10-18 08:03

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dprwuhawr/image/upload/v1728385884/media/images/default_profile_b0dubq.jpg', max_length=255, verbose_name='image'),
        ),
    ]
