# Generated by Django 4.2 on 2025-02-09 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0007_alter_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="allergy_type",
            field=models.CharField(
                choices=[
                    ("none", "No Specific Allergy"),
                    ("milk", "Milk Allergy"),
                    ("nuts", "Nut Allergy"),
                    ("wheat", "Wheat Allergy"),
                    ("eggs", "Egg Allergy"),
                    ("shellfish", "Shellfish Allergy"),
                    ("dairy", "Dairy Allergy"),
                ],
                default="none",
                max_length=20,
            ),
        ),
    ]
