# Generated by Django 5.1.1 on 2024-10-22 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='https://res.cloudinary.com/dprwuhawr/image/upload/v1729293609/default_profile_xysrop.jpg', upload_to='images/'),
        ),
    ]
