# Generated by Django 5.1.1 on 2024-10-25 05:31

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=cloudinary.models.CloudinaryField(default='../default_profile_xysrop', max_length=255, verbose_name='image'),
        ),
    ]
