# Generated by Django 4.2 on 2024-12-18 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["-created_at", "category"]},
        ),
        migrations.AddField(
            model_name="comment",
            name="category",
            field=models.CharField(
                choices=[
                    ("general", "General"),
                    ("question", "Question"),
                    ("tip", "Tip"),
                ],
                default="general",
                max_length=50,
            ),
        ),
    ]
