# Generated by Django 4.2 on 2024-12-20 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("followers", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="follower",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="follower",
            constraint=models.UniqueConstraint(
                fields=("owner", "followed"), name="unique_follower"
            ),
        ),
    ]
