# Generated by Django 5.1.1 on 2024-10-30 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                default="../default_post_p5tht5",
                null=True,
                upload_to="images/",
            ),
        ),
    ]
