# Generated by Django 5.1.1 on 2024-11-02 10:39

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_category_alter_product_image_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                default="default_product_p5tht5",
                max_length=255,
                null=True,
                verbose_name="image",
            ),
        ),
    ]
