# Generated by Django 4.2 on 2024-12-27 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                default="../default_product_vjeszy",
                null=True,
                upload_to="images/",
            ),
        ),
    ]
